{"id":"google/devtools/clouderrorreporting/v1beta1/errorcontext","name":"ErrorContext","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext"],"description":"<p>A description of the context in which an error occurred.\nThis data should be provided by the application when reporting an error,\nunless the\nerror report has been generated automatically from Google App Engine logs.</p>","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"methods":[{"id":"http_request-instance","type":"instance","name":"http_request","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#http_request"],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"google/devtools/clouderrorreporting/v1beta1/httprequestcontext\">Google::Devtools::Clouderrorreporting::V1beta1::HttpRequestContext</a>"],"description":"The HTTP request which was processed when the error was\ntriggered."}]},{"id":"http_request=-instance","type":"instance","name":"http_request=","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#http_request="],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"google/devtools/clouderrorreporting/v1beta1/httprequestcontext\">Google::Devtools::Clouderrorreporting::V1beta1::HttpRequestContext</a>"],"description":"The HTTP request which was processed when the error was\ntriggered."}]},{"id":"user-instance","type":"instance","name":"user","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#user"],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["String"],"description":"The user who caused or was affected by the crash.\nThis can be a user ID, an email address, or an arbitrary token that\nuniquely identifies the user.\nWhen sending an error report, leave this field empty if the user was not\nlogged in. In this case the\nError Reporting system will use other data, such as remote IP address, to\ndistinguish affected users. See +affected_users_count+ in\n+ErrorGroupStats+."}]},{"id":"user=-instance","type":"instance","name":"user=","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#user="],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["String"],"description":"The user who caused or was affected by the crash.\nThis can be a user ID, an email address, or an arbitrary token that\nuniquely identifies the user.\nWhen sending an error report, leave this field empty if the user was not\nlogged in. In this case the\nError Reporting system will use other data, such as remote IP address, to\ndistinguish affected users. See +affected_users_count+ in\n+ErrorGroupStats+."}]},{"id":"report_location-instance","type":"instance","name":"report_location","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#report_location"],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"google/devtools/clouderrorreporting/v1beta1/sourcelocation\">Google::Devtools::Clouderrorreporting::V1beta1::SourceLocation</a>"],"description":"The location in the source code where the decision was made to\nreport the error, usually the place where it was logged.\nFor a logged exception this would be the source line where the\nexception is logged, usually close to the place where it was\ncaught. This value is in contrast to +Exception.cause_location+,\nwhich describes the source line where the exception was thrown."}]},{"id":"report_location=-instance","type":"instance","name":"report_location=","title":["Google","Devtools","Clouderrorreporting","V1beta1","ErrorContext#report_location="],"description":"","source":"google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb#L135","resources":[],"examples":[],"params":[],"exceptions":[],"returns":[{"types":["<a data-custom-type=\"google/devtools/clouderrorreporting/v1beta1/sourcelocation\">Google::Devtools::Clouderrorreporting::V1beta1::SourceLocation</a>"],"description":"The location in the source code where the decision was made to\nreport the error, usually the place where it was logged.\nFor a logged exception this would be the source line where the\nexception is logged, usually close to the place where it was\ncaught. This value is in contrast to +Exception.cause_location+,\nwhich describes the source line where the exception was thrown."}]}]}